title: Git Básico e alguns serviços
description: Slides do workshop 'Git básico e alguns serviços', a ser apresentado na Campus Party Natal em 2019.
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
